### ISSUE TITLE
Problem when plotting in Comparison widget

### ISSUE THREAD

**Issue by jureyherrera** [srio/OASYS1-SHADOW4#2]
When selecting **show plots : Yes** in the Shadow3 Shadow4 Comparison widget, we can see some plots but also the following error:

`NameError                                     Traceback (most recent call last):
  File "C:\...\OASYS1-SHADOW4\orangecontrib\shadow4\widgets\compatibility\ow_shadow_compare_beam3_beam4.py", line 335, in compare_beams
    check_six_columns_mean_and_std(beam3, beam4, do_assert=self.columns_6_assert, do_plot=self.columns_6_plot)
  File "C:\...\OASYS1-SHADOW4\orangecontrib\shadow4\widgets\compatibility\ow_shadow_compare_beam3_beam4.py", line 51, in check_six_columns_mean_and_std
    b3 = Shadow.Beam()
NameError: name 'Shadow' is not defined`

Best, J

**Comment by jureyherrera** [comment]
Now is working very well. Thank you
